default_config:
wake_on_lan:
shopping_list:

recorder:
  purge_keep_days: 30
  db_url: !secret maria_db_url

tts:
  - platform: marytts
    host: 192.168.1.32

webostv:
  host: 192.168.1.12
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 00:51:ED:C5:57:86
  name: Living Room TV
  customize:
    sources:
      - Amazon Prime Video
      - Apple tv
      - Netflix
      - Play station
      - Plex
      - Stan
      - Switch
      - YouTube

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

google_assistant:
  project_id: hassio-home-assistant-288123
  service_account: !include service-account.json
  report_state: true
  exposed_domains:
    - switch
    - light

device_tracker:
  - platform: tomato
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    http_id: !secret router_http_id

anniversaries:
  sensors:
    - name: Move In Date
      date: "2020-11-20"
      
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistantpassword
  max_retries: 3
  default_measurement: state

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret linus_telegram_chat_id

automation: !include automations.yaml
binary_sensor: !include binarysensors.yaml
group: !include groups.yaml
light: !include lights.yaml
notify: !include notifies.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml